### ISSUE TITLE
advertising

### ISSUE THREAD

**Issue by canis76** [ieee8023/PDFViewer#17]
I paid for this because it's useful. However, I just received an advertisement. I thought that stopped after purchase.

**Comment by ieee8023** [comment]
The version on Google play is not this one. You can install the open source build here: https://github.com/ieee8023/PDFViewer/blob/master/builds/PDFViewer3.apk

**Comment by canis76** [comment]
So you are telling me that I wasted my money.  Paying for the product will get you no support on official channels?

**Comment by ieee8023** [comment]
I don't know what you paid for. You should follow up with Google if you paid for something on Google Play and the service was not rendered.
